/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_AnalisisNumerico_lib_DefMatrizJni */

#ifndef _Included_lib_AnalisisNumerico_lib_DefMatrizJni
#define _Included_lib_AnalisisNumerico_lib_DefMatrizJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_AnalisisNumerico_lib_DefMatrizJni
 * Method:    resolverMatriz
 * Signature: ([FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_lib_1AnalisisNumerico_lib_DefMatrizJni_resolverMatriz
  (JNIEnv *, jobject, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
